TrajectoryPlannerROS:

# Robot Configuration Parameters
  holonomic_robot: false

  max_vel_x: 3.0
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta:  0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.1

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.15

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.2 

# Trajectory Scoring Parameters
  meter_scoring: true
