map_type: costmap
robot_base_frame: robot_footprint

obstacle_range: 3.0
raytrace_range: 4.0
transform_tolerance: 0.5
robot_radius: 0.5
inflation_radius: 0.30

observation_sources: laser_scan_sensor

laser_scan_sensor: {
  sensor_frame: hokuyo,
  data_type: LaserScan,
  topic: /udacity_bot/laser/scan,
  marking: true,
  clearing: true
}
